services:
  # Remove the app and nginx services since we don't need them for tests
  app: !reset null
  nginx: !reset null

  app-test:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
      args:
        CI_BUILD: "true"      
    image: mampftest:image
    volumes:
      # Anonymous volume for the public folder where the assets are compiled to
      - "/workspaces/mampf/public/"
