---
version: '3.2'
services:
  redis:
    image: "redis:alpine"

  solr:
    image: "solr:8"
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - type: bind
        source: ../../solr/development/conf/
        target: /solrconfig/
        read_only: true
    command: ["solr-precreate", "test", "/solrconfig"]

  db:
    image: postgres
    environment:
      - POSTGRES_USER=mampf
      - POSTGRES_HOST_AUTH_METHOD=trust

  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:latest
    ports:
      - "127.0.0.1:1080:1080"

  mampf:
    build:
      context: ./../..
      dockerfile: docker/run_cypress_tests/Dockerfile
    image: mampf:development
    ports:
      - "127.0.0.1:3000:3000"
    # TODO: Use this
    # entrypoint: /usr/src/app/docker/run_cypress_tests/run_tests.sh
    entrypoint: /usr/src/app/entrypoint.sh
    environment:
      RAILS_ENV: test
      TEST_DATABASE_ADAPTER: postgresql
      TEST_DATABASE_DATABASE: mampf
      TEST_DATABASE_INTERACTIONS: interactions
      TEST_DATABASE_USERNAME: mampf
      TEST_DATABASE_HOST: db
      TEST_DATABASE_PORT: 5432
      MAILSERVER: mailcatcher
      FROM_ADDRESS: development@localhost
      URL_HOST: localhost
      SECRET_KEY_BASE: testenvironment
      ERDBEERE_SERVER: https://erdbeere.mathi.uni-heidelberg.de
      ERDBEERE_API: https://erdbeere.mathi.uni-heidelberg.de/api/v1
      MUESLI_SERVER: https://muesli.mathi.uni-heidelberg.de
      PROJECT_EMAIL: project@localhost
      PROJECT_NOTIFICATION_EMAIL: project+notification@localhost
      MEDIA_FOLDER: mampf
      REDIS_URL: redis://redis:6379/1
      SOLR_PATH: /solr/test
      SPROCKETS_CACHE: /cache
    depends_on:
      - db
      - solr
      - redis
      - mailcatcher

  cypress_runner:
    image: cypress/included:5.2.0
    environment:
      CYPRESS_baseUrl: http://mampf:3000
    entrypoint: bash -c "while ! curl -s $$CYPRESS_baseUrl > /dev/null; do echo waiting for MaMpf to come online at $$CYPRESS_baseUrl; sleep 1; done; npx cypress run $$@"
    volumes:
      - ../../spec/cypress/integration:/cypress/integration:ro
      - ../../spec/cypress/support:/cypress/support:ro
      - ../../spec/cypress.json:/cypress.json:ro
      - ../../.git:/.git:ro
      # cypress outputs are saved here (needed only locally)
      #- ../../cypress/videos:/cypress/videos
      #- ../../cypress/screenshots:/cypress/screenshots
    depends_on:
      - mampf
