services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started

  mimir:
    image: grafana/mimir
    volumes:
      - ../monitoring/mimir.yml:/etc/mimir.yml
      - mimir-data:/data
    command: 
      - "-config.file=/etc/mimir.yml"
      - "-target=all"
    ports:
      - "9009:9009"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    volumes:
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "2345:2345"
    environment:
      - GF_SERVER_HTTP_PORT=2345
    restart: unless-stopped

volumes:
  mimir-data: